server:
  grpc:
    addr: 0.0.0.0:9000
    timeout: 60s
service:
  codeGenerator:
    dataCollectionTmplRoot: /etc/data-collection-template
    dataProcessingTmplRoot: /etc/data-processing-template
  compiler:
    timeout: 600s
    dataCollection:
      projectDir: /var/data-collection
      apiDir: api/dataCollection/v1
      serviceDir: internal/service
    dataProcessing:
      projectDir: /var/data-processing
      apiDir: api/dataProcessing/v1
      serviceDir: internal/service
