logLevel: INFO
server:
  grpc:
    addr: 0.0.0.0:9000
    timeout: 600s
service:
  codeGenerator:
    dataCollectionTmplRoot: /app/compilation-center/internal/biz/codegenerator/data-collection-template
    dataProcessingTmplRoot: /app/compilation-center/internal/biz/codegenerator/data-processing-template
  compiler:
    timeout: 600s
    dataCollection:
      projectDir: /app/compilation-center/compile_project/data-collection
      apiDir: api/dataCollection/v1
      serviceDir: internal/service
    dataProcessing:
      projectDir: /app/compilation-center/compile_project/data-processing
      apiDir: api/dataProcessing/v1
      serviceDir: internal/service
data:
  redis:
    host: test-redis.test.svc.cluster.local
    serverPort: 6379
    sentinelPort: 26379
    masterName: mymaster
    poolSize: 5
    minIdleConns: 2