// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package test

import (
	"gitee.com/moyusir/compilation-center/internal/biz"
	"gitee.com/moyusir/compilation-center/internal/conf"
	"gitee.com/moyusir/compilation-center/internal/server"
	"gitee.com/moyusir/compilation-center/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confService *conf.Service, logger log.Logger) (*kratos.App, error) {
	buildUsecase, err := biz.NewBuildUsecase(confService)
	if err != nil {
		return nil, err
	}
	buildService := service.NewBuildService(buildUsecase)
	grpcServer := server.NewGRPCServer(confServer, buildService, logger)
	app := newApp(logger, grpcServer)
	return app, nil
}
